services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_sql:/docker-entrypoint-initdb.d

  api:
    build: .
    container_name: ktor_api
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  db_data: